<?php

use App\Http\Controllers\Api\V1\AppDownloadController;
use App\Http\Controllers\Api\V1\ApplicationComplianceController;
use App\Http\Controllers\Api\V1\ApplicationDocumentController;
use App\Http\Controllers\Api\V1\ApplicationExportController;
use App\Http\Controllers\Api\V1\AreaController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BranchController;
use App\Http\Controllers\Api\V1\CreditReviewController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\DataPurgeController;
use App\Http\Controllers\Api\V1\GroupController;
use App\Http\Controllers\Api\V1\GroupPortfolioController;
use App\Http\Controllers\Api\V1\GroupVisitController;
use App\Http\Controllers\Api\V1\LoanAdministrationController;
use App\Http\Controllers\Api\V1\LoanApplicationController;
use App\Http\Controllers\Api\V1\LoanApplicationWorkflowController;
use App\Http\Controllers\Api\V1\LoanCalculatorController;
use App\Http\Controllers\Api\V1\LoanController;
use App\Http\Controllers\Api\V1\LoanDisbursementController;
use App\Http\Controllers\Api\V1\LoanExportController;
use App\Http\Controllers\Api\V1\LoanGroupWitnessController;
use App\Http\Controllers\Api\V1\LoanProductController;
use App\Http\Controllers\Api\V1\LoanSettlementController;
use App\Http\Controllers\Api\V1\MemberController;
use App\Http\Controllers\Api\V1\MemberDocumentController;
use App\Http\Controllers\Api\V1\MemberExportController;
use App\Http\Controllers\Api\V1\MemberKycController;
use App\Http\Controllers\Api\V1\MemberPassbookController;
use App\Http\Controllers\Api\V1\MemberPhotoController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OnboardingController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PortfolioController;
use App\Http\Controllers\Api\V1\RegionController;
use App\Http\Controllers\Api\V1\SecurityAccountController;
use App\Http\Controllers\Api\V1\SystemSettingsController;
use App\Http\Controllers\Api\V1\UserAttachmentController;
use App\Http\Controllers\Api\V1\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:5,1');
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');

    Route::get('app/latest', [AppDownloadController::class, 'latest'])->name('app.latest');
    Route::get('app/update-check', [AppDownloadController::class, 'updateCheck'])->name('api.app.update-check');
    Route::get('app/{appVersion}/download', [AppDownloadController::class, 'download'])->name('api.app.download');

    Route::middleware(['auth:sanctum'])->group(function () {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::post('auth/change-password', [AuthController::class, 'changePassword']);
        Route::get('profile', [AuthController::class, 'profile']);
        Route::get('dashboard', [DashboardController::class, 'index']);
        Route::get('portfolio/summary', [PortfolioController::class, 'summary']);
        Route::get('portfolio/branches', [PortfolioController::class, 'branches']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/read-all', [NotificationController::class, 'readAll']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'read']);

        Route::post('onboarding/groups', [OnboardingController::class, 'group']);
        Route::post('onboarding/members', [OnboardingController::class, 'member']);
        Route::post('onboarding/loan-applications', [OnboardingController::class, 'loanApplication']);

        Route::get('regions', [RegionController::class, 'index'])->name('regions.index');
        Route::post('regions', [RegionController::class, 'store'])->name('regions.store');
        Route::get('regions/{region}', [RegionController::class, 'show'])->name('regions.show');
        Route::match(['POST', 'PUT', 'PATCH'], 'regions/{region}', [RegionController::class, 'update'])->name('regions.update');
        Route::delete('regions/{region}', [RegionController::class, 'destroy'])->name('regions.destroy');
        Route::get('areas', [AreaController::class, 'index'])->name('areas.index');
        Route::post('areas', [AreaController::class, 'store'])->name('areas.store');
        Route::get('areas/{area}', [AreaController::class, 'show'])->name('areas.show');
        Route::match(['POST', 'PUT', 'PATCH'], 'areas/{area}', [AreaController::class, 'update'])->name('areas.update');
        Route::delete('areas/{area}', [AreaController::class, 'destroy'])->name('areas.destroy');
        Route::get('branches', [BranchController::class, 'index'])->name('branches.index');
        Route::post('branches', [BranchController::class, 'store'])->name('branches.store');
        Route::get('branches/{branch}', [BranchController::class, 'show'])->name('branches.show');
        Route::match(['POST', 'PUT', 'PATCH'], 'branches/{branch}', [BranchController::class, 'update'])->name('branches.update');
        Route::delete('branches/{branch}', [BranchController::class, 'destroy'])->name('branches.destroy');
        Route::get('roles', [UserController::class, 'roles']);
        Route::get('users', [UserController::class, 'index'])->name('users.index');
        Route::post('users', [UserController::class, 'store'])->name('users.store');
        Route::get('users/{user}', [UserController::class, 'show'])->name('users.show');
        Route::match(['POST', 'PUT', 'PATCH'], 'users/{user}', [UserController::class, 'update'])->name('users.update');
        Route::delete('users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
        Route::get('users/{user}/attachments', [UserAttachmentController::class, 'index']);
        Route::post('users/{user}/attachments', [UserAttachmentController::class, 'store']);
        Route::get('users/{user}/attachments/{userAttachment}/download', [UserAttachmentController::class, 'download'])->name('api.users.attachments.download');
        Route::delete('users/{user}/attachments/{userAttachment}', [UserAttachmentController::class, 'destroy']);
        Route::get('groups', [GroupController::class, 'index']);
        Route::post('groups', [GroupController::class, 'store']);
        Route::get('groups/{group}', [GroupController::class, 'show']);
        Route::match(['POST', 'PUT'], 'groups/{group}', [GroupController::class, 'update']);
        Route::delete('groups/{group}', [GroupController::class, 'destroy'])->name('groups.destroy');
        Route::post('groups/{group}/delete', [GroupController::class, 'destroy']);
        Route::get('groups/{group}/members', [GroupController::class, 'members']);
        Route::get('groups/{group}/dashboard', [GroupPortfolioController::class, 'dashboard']);
        Route::get('groups/{group}/statistics', [GroupPortfolioController::class, 'statistics']);
        Route::get('groups/{group}/loans', [GroupPortfolioController::class, 'loans']);
        Route::get('groups/{group}/applications', [GroupPortfolioController::class, 'applications']);
        Route::get('groups/{group}/collections', [GroupPortfolioController::class, 'collections']);
        Route::get('groups/{group}/meetings', [GroupPortfolioController::class, 'meetings']);
        Route::get('group-visits', [GroupVisitController::class, 'index'])->name('group-visits.index');
        Route::post('group-visits', [GroupVisitController::class, 'store'])->name('group-visits.store');
        Route::get('group-visits/{group_visit}', [GroupVisitController::class, 'show'])->name('group-visits.show');
        Route::match(['POST', 'PUT', 'PATCH'], 'group-visits/{group_visit}', [GroupVisitController::class, 'update'])->name('group-visits.update');
        Route::post('group-visits/{group_visit}/delete', [GroupVisitController::class, 'destroy'])->name('group-visits.delete');
        Route::get('members', [MemberController::class, 'index'])->name('members.index');
        Route::get('members/{member}', [MemberController::class, 'show'])->name('members.show');
        Route::post('members', [MemberController::class, 'store'])->name('members.store');
        Route::match(['POST', 'PUT', 'PATCH'], 'members/{member}', [MemberController::class, 'update'])->name('members.update');
        Route::post('members/{member}/delete', [MemberController::class, 'destroy'])->name('members.delete');
        Route::match(['POST', 'PUT'], 'members/{member}/kyc', [MemberKycController::class, 'update']);
        Route::post('members/{member}/photo', [MemberPhotoController::class, 'store']);
        Route::get('members/{member}/passbook', [MemberPassbookController::class, 'show']);
        Route::get('members/{member}/export', [MemberExportController::class, 'download']);
        Route::get('members/{member}/documents', [MemberDocumentController::class, 'index']);
        Route::post('members/{member}/documents', [MemberDocumentController::class, 'store']);
        Route::get('members/{member}/documents/{memberDocument}/view', [MemberDocumentController::class, 'view'])->name('api.members.documents.view');
        Route::get('members/{member}/documents/{memberDocument}/download', [MemberDocumentController::class, 'download'])->name('api.members.documents.download');
        Route::post('members/{member}/documents/{memberDocument}', [MemberDocumentController::class, 'show']);
        Route::delete('members/{member}/documents/{memberDocument}', [MemberDocumentController::class, 'destroy'])->name('api.members.documents.destroy');
        Route::post('members/{member}/documents/{memberDocument}/delete', [MemberDocumentController::class, 'destroy'])->name('api.members.documents.delete');
        Route::get('members/{member}/security', [SecurityAccountController::class, 'show']);
        Route::post('members/{member}/security-transactions', [SecurityAccountController::class, 'store']);
        Route::post('members/{member}/security-payoff', [SecurityAccountController::class, 'payOff'])->name('members.security-payoff');

        Route::get('loan-products', [LoanProductController::class, 'index'])->name('loan-products.index');
        Route::get('loan-products/{loan_product}', [LoanProductController::class, 'show'])->name('loan-products.show');
        Route::post('loan-products', [LoanProductController::class, 'store'])->name('loan-products.store');
        Route::match(['POST', 'PUT', 'PATCH'], 'loan-products/{loan_product}', [LoanProductController::class, 'update'])->name('loan-products.update');
        Route::delete('loan-products/{loan_product}', [LoanProductController::class, 'destroy'])->name('loan-products.destroy');
        Route::post('loan-calculator', [LoanCalculatorController::class, 'calculate']);
        Route::get('loan-applications', [LoanApplicationController::class, 'index'])->name('loan-applications.index');
        Route::get('loan-applications/{loan_application}', [LoanApplicationController::class, 'show'])->name('loan-applications.show');
        Route::post('loan-applications', [LoanApplicationController::class, 'store'])->name('loan-applications.store');
        Route::match(['POST', 'PUT', 'PATCH'], 'loan-applications/{loan_application}', [LoanApplicationController::class, 'update'])->name('loan-applications.update');
        Route::post('loan-applications/{loan_application}/delete', [LoanApplicationController::class, 'destroy'])->name('loan-applications.delete');
        Route::post('loan-applications/{loanApplication}/submit', [LoanApplicationWorkflowController::class, 'submit']);
        Route::post('loan-applications/{loanApplication}/approve', [LoanApplicationWorkflowController::class, 'approve']);
        Route::post('loan-applications/{loanApplication}/reject', [LoanApplicationWorkflowController::class, 'reject']);
        Route::post('loan-applications/{loanApplication}/assign-credit-officer', [CreditReviewController::class, 'assign']);
        Route::post('loan-applications/{loanApplication}/credit-review', [CreditReviewController::class, 'store']);
        Route::post('loan-applications/{loanApplication}/return', [CreditReviewController::class, 'returnApplication']);
        Route::match(['POST', 'PUT'], 'loan-applications/{loanApplication}/compliance/applicant', [ApplicationComplianceController::class, 'applicant']);
        Route::post('loan-applications/{loanApplication}/compliance/guarantors', [ApplicationComplianceController::class, 'guarantor']);
        Route::match(['POST', 'PUT'], 'loan-applications/{loanApplication}/compliance/nominees', [ApplicationComplianceController::class, 'nominees']);
        Route::post('loan-applications/{loanApplication}/compliance/documents', [ApplicationComplianceController::class, 'document']);
        Route::post('loan-applications/{loanApplication}/compliance/documents/{loanDocument}/verify', [ApplicationComplianceController::class, 'verifyDocument']);
        Route::get('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'store']);
        Route::post('loan-applications/{loanApplication}/documents/{loanDocument}/verify', [ApplicationDocumentController::class, 'verify']);
        Route::post('loan-applications/{loanApplication}/documents/{loanDocument}/delete', [ApplicationDocumentController::class, 'destroy'])->name('api.loan-applications.documents.delete');
        Route::get('loan-applications/{loanApplication}/documents/{loanDocument}/view', [ApplicationDocumentController::class, 'view'])->name('api.loan-applications.documents.view');
        Route::get('loan-applications/{loanApplication}/documents/{loanDocument}/download', [ApplicationDocumentController::class, 'download'])->name('api.loan-applications.documents.download');
        Route::get('loan-applications/{loanApplication}/export', [ApplicationExportController::class, 'download']);
        Route::post('loan-applications/{loanApplication}/cancel', [ApplicationComplianceController::class, 'cancel']);
        Route::get('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'store']);

        Route::get('loans', [LoanController::class, 'index']);
        Route::get('loans/{loan}', [LoanController::class, 'show']);
        Route::get('loans/{loan}/schedule', [LoanController::class, 'schedule']);
        Route::get('loans/{loan}/export', [LoanExportController::class, 'download']);
        Route::post('loans/{loan}/disburse', [LoanDisbursementController::class, 'store']);
        Route::post('loans/{loan}/payments', [PaymentController::class, 'store']);
        Route::match(['POST', 'PUT', 'PATCH'], 'payments/{payment}', [PaymentController::class, 'update']);
        Route::post('payments/{payment}/reverse', [PaymentController::class, 'reverse']);
        Route::post('loans/{loan}/settle', [LoanSettlementController::class, 'store']);
        Route::post('members/{member}/passbook-replacements', [LoanAdministrationController::class, 'replacePassbook']);
        Route::post('loans/{loan}/default-notices', [LoanAdministrationController::class, 'defaultNotice']);
        Route::post('loans/{loan}/clearance', [LoanAdministrationController::class, 'clearance']);

        Route::prefix('system')->group(function () {
            Route::get('settings', [SystemSettingsController::class, 'index'])->name('api.system.settings.index');
            Route::match(['POST', 'PUT'], 'settings', [SystemSettingsController::class, 'update'])->name('api.system.settings.update');
            Route::get('audit-logs', [AuditLogController::class, 'index'])->name('api.system.audit-logs.index');
            Route::get('audit-logs/{id}', [AuditLogController::class, 'show'])->name('api.system.audit-logs.show');
            Route::get('data/summary', [DataPurgeController::class, 'summary'])->name('api.system.data.summary');
            Route::post('data/preview', [DataPurgeController::class, 'preview'])->name('api.system.data.preview');
        });
        Route::post('system/data/purge', [DataPurgeController::class, 'purge'])->name('api.system.data.purge');
    });
});
