<?php

use App\Http\Controllers\Api\V1\ApplicationComplianceController;
use App\Http\Controllers\Api\V1\ApplicationDocumentController;
use App\Http\Controllers\Api\V1\ApplicationExportController;
use App\Http\Controllers\Api\V1\AreaController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BranchController;
use App\Http\Controllers\Api\V1\CreditReviewController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\GroupController;
use App\Http\Controllers\Api\V1\GroupPortfolioController;
use App\Http\Controllers\Api\V1\GroupVisitController;
use App\Http\Controllers\Api\V1\LoanAdministrationController;
use App\Http\Controllers\Api\V1\LoanApplicationController;
use App\Http\Controllers\Api\V1\LoanApplicationWorkflowController;
use App\Http\Controllers\Api\V1\LoanCalculatorController;
use App\Http\Controllers\Api\V1\LoanController;
use App\Http\Controllers\Api\V1\LoanDisbursementController;
use App\Http\Controllers\Api\V1\LoanExportController;
use App\Http\Controllers\Api\V1\LoanGroupWitnessController;
use App\Http\Controllers\Api\V1\LoanProductController;
use App\Http\Controllers\Api\V1\LoanSettlementController;
use App\Http\Controllers\Api\V1\MemberController;
use App\Http\Controllers\Api\V1\MemberDocumentController;
use App\Http\Controllers\Api\V1\MemberExportController;
use App\Http\Controllers\Api\V1\MemberKycController;
use App\Http\Controllers\Api\V1\MemberPassbookController;
use App\Http\Controllers\Api\V1\MemberPhotoController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OnboardingController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PortfolioController;
use App\Http\Controllers\Api\V1\RegionController;
use App\Http\Controllers\Api\V1\SecurityAccountController;
use App\Http\Controllers\Api\V1\SystemSettingsController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\DataPurgeController;
use App\Http\Controllers\Api\V1\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:5,1');
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');

    Route::middleware(['auth:sanctum', 'branch.access'])->group(function () {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('profile', [AuthController::class, 'profile']);
        Route::get('dashboard', [DashboardController::class, 'index']);
        Route::get('portfolio/summary', [PortfolioController::class, 'summary']);
        Route::get('portfolio/branches', [PortfolioController::class, 'branches']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/read-all', [NotificationController::class, 'readAll']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'read']);

        Route::post('onboarding/groups', [OnboardingController::class, 'group']);
        Route::post('onboarding/members', [OnboardingController::class, 'member']);
        Route::post('onboarding/loan-applications', [OnboardingController::class, 'loanApplication']);

        Route::apiResource('regions', RegionController::class);
        Route::apiResource('areas', AreaController::class);
        Route::apiResource('branches', BranchController::class);
        Route::get('roles', [UserController::class, 'roles']);
        Route::apiResource('users', UserController::class);
        Route::apiResource('groups', GroupController::class)->only(['index', 'show']);
        Route::apiResource('groups', GroupController::class)->only('store');
        Route::apiResource('groups', GroupController::class)->only(['update', 'destroy']);
        Route::get('groups/{group}/members', [GroupController::class, 'members']);
        Route::get('groups/{group}/dashboard', [GroupPortfolioController::class, 'dashboard']);
        Route::get('groups/{group}/loans', [GroupPortfolioController::class, 'loans']);
        Route::get('groups/{group}/applications', [GroupPortfolioController::class, 'applications']);
        Route::get('groups/{group}/collections', [GroupPortfolioController::class, 'collections']);
        Route::get('groups/{group}/meetings', [GroupPortfolioController::class, 'meetings']);
        Route::apiResource('group-visits', GroupVisitController::class);
        Route::apiResource('members', MemberController::class)->only(['index', 'show']);
        Route::apiResource('members', MemberController::class)->only('store');
        Route::apiResource('members', MemberController::class)->only('update');
        Route::apiResource('members', MemberController::class)->only('destroy');
        Route::put('members/{member}/kyc', [MemberKycController::class, 'update']);
        Route::post('members/{member}/photo', [MemberPhotoController::class, 'store']);
        Route::get('members/{member}/passbook', [MemberPassbookController::class, 'show']);
        Route::get('members/{member}/export', [MemberExportController::class, 'download']);
        Route::get('members/{member}/documents', [MemberDocumentController::class, 'index']);
        Route::post('members/{member}/documents', [MemberDocumentController::class, 'store']);
        Route::get('members/{member}/documents/{memberDocument}/download', [MemberDocumentController::class, 'download'])->name('api.members.documents.download');
        Route::delete('members/{member}/documents/{memberDocument}', [MemberDocumentController::class, 'destroy']);
        Route::get('members/{member}/security', [SecurityAccountController::class, 'show']);
        Route::post('members/{member}/security-transactions', [SecurityAccountController::class, 'store']);

        Route::apiResource('loan-products', LoanProductController::class)->only(['index', 'show']);
        Route::apiResource('loan-products', LoanProductController::class)->only(['store', 'update', 'destroy']);
        Route::post('loan-calculator', [LoanCalculatorController::class, 'calculate']);
        Route::apiResource('loan-applications', LoanApplicationController::class)->only(['index', 'show']);
        Route::apiResource('loan-applications', LoanApplicationController::class)->only(['store', 'update', 'destroy']);
        Route::post('loan-applications/{loanApplication}/submit', [LoanApplicationWorkflowController::class, 'submit']);
        Route::post('loan-applications/{loanApplication}/approve', [LoanApplicationWorkflowController::class, 'approve']);
        Route::post('loan-applications/{loanApplication}/reject', [LoanApplicationWorkflowController::class, 'reject']);
        Route::post('loan-applications/{loanApplication}/assign-credit-officer', [CreditReviewController::class, 'assign']);
        Route::post('loan-applications/{loanApplication}/credit-review', [CreditReviewController::class, 'store']);
        Route::post('loan-applications/{loanApplication}/return', [CreditReviewController::class, 'returnApplication']);
        Route::put('loan-applications/{loanApplication}/compliance/applicant', [ApplicationComplianceController::class, 'applicant']);
        Route::post('loan-applications/{loanApplication}/compliance/guarantors', [ApplicationComplianceController::class, 'guarantor']);
        Route::put('loan-applications/{loanApplication}/compliance/nominees', [ApplicationComplianceController::class, 'nominees']);
        Route::post('loan-applications/{loanApplication}/compliance/documents', [ApplicationComplianceController::class, 'document']);
        Route::post('loan-applications/{loanApplication}/compliance/documents/{loanDocument}/verify', [ApplicationComplianceController::class, 'verifyDocument']);
        Route::get('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'store']);
        Route::post('loan-applications/{loanApplication}/documents/{loanDocument}/verify', [ApplicationDocumentController::class, 'verify']);
        Route::get('loan-applications/{loanApplication}/documents/{loanDocument}/download', [ApplicationDocumentController::class, 'download'])->name('api.loan-applications.documents.download');
        Route::get('loan-applications/{loanApplication}/export', [ApplicationExportController::class, 'download']);
        Route::post('loan-applications/{loanApplication}/cancel', [ApplicationComplianceController::class, 'cancel']);
        Route::get('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'store']);

        Route::get('loans', [LoanController::class, 'index']);
        Route::get('loans/{loan}', [LoanController::class, 'show']);
        Route::get('loans/{loan}/schedule', [LoanController::class, 'schedule']);
        Route::get('loans/{loan}/export', [LoanExportController::class, 'download']);
        Route::post('loans/{loan}/disburse', [LoanDisbursementController::class, 'store']);
        Route::post('loans/{loan}/payments', [PaymentController::class, 'store']);
        Route::post('payments/{payment}/reverse', [PaymentController::class, 'reverse']);
        Route::post('loans/{loan}/settle', [LoanSettlementController::class, 'store']);
        Route::post('members/{member}/passbook-replacements', [LoanAdministrationController::class, 'replacePassbook']);
        Route::post('loans/{loan}/default-notices', [LoanAdministrationController::class, 'defaultNotice']);
        Route::post('loans/{loan}/clearance', [LoanAdministrationController::class, 'clearance']);

        Route::prefix('system')->group(function () {
            Route::get('settings', [SystemSettingsController::class, 'index'])->name('api.system.settings.index');
            Route::put('settings', [SystemSettingsController::class, 'update'])->name('api.system.settings.update');
            Route::get('audit-logs', [AuditLogController::class, 'index'])->name('api.system.audit-logs.index');
            Route::get('audit-logs/{id}', [AuditLogController::class, 'show'])->name('api.system.audit-logs.show');
            Route::get('data/summary', [DataPurgeController::class, 'summary'])->name('api.system.data.summary');
            Route::post('data/preview', [DataPurgeController::class, 'preview'])->name('api.system.data.preview');
        });
        Route::post('system/data/purge', [DataPurgeController::class, 'purge'])->name('api.system.data.purge');
    });
});
