<?php

use App\Http\Controllers\Api\V1\ApplicationComplianceController;
use App\Http\Controllers\Api\V1\ApplicationDocumentController;
use App\Http\Controllers\Api\V1\ApplicationExportController;
use App\Http\Controllers\Api\V1\AreaController;
use App\Http\Controllers\Api\V1\AppDownloadController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BranchController;
use App\Http\Controllers\Api\V1\CreditReviewController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\GroupController;
use App\Http\Controllers\Api\V1\GroupPortfolioController;
use App\Http\Controllers\Api\V1\GroupVisitController;
use App\Http\Controllers\Api\V1\LoanAdministrationController;
use App\Http\Controllers\Api\V1\LoanApplicationController;
use App\Http\Controllers\Api\V1\LoanApplicationWorkflowController;
use App\Http\Controllers\Api\V1\LoanCalculatorController;
use App\Http\Controllers\Api\V1\LoanController;
use App\Http\Controllers\Api\V1\LoanDisbursementController;
use App\Http\Controllers\Api\V1\LoanExportController;
use App\Http\Controllers\Api\V1\LoanGroupWitnessController;
use App\Http\Controllers\Api\V1\LoanProductController;
use App\Http\Controllers\Api\V1\LoanSettlementController;
use App\Http\Controllers\Api\V1\MemberController;
use App\Http\Controllers\Api\V1\MemberDocumentController;
use App\Http\Controllers\Api\V1\MemberExportController;
use App\Http\Controllers\Api\V1\MemberKycController;
use App\Http\Controllers\Api\V1\MemberPassbookController;
use App\Http\Controllers\Api\V1\MemberPhotoController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OnboardingController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PortfolioController;
use App\Http\Controllers\Api\V1\RegionController;
use App\Http\Controllers\Api\V1\SecurityAccountController;
use App\Http\Controllers\Api\V1\SystemSettingsController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\DataPurgeController;
use App\Http\Controllers\Api\V1\UserController;
use App\Http\Controllers\Api\V1\UserAttachmentController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:5,1');
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');

    Route::get('app/latest', [AppDownloadController::class, 'latest'])->name('app.latest');
    Route::get('app/{appVersion}/download', [AppDownloadController::class, 'download'])->name('api.app.download');

    Route::middleware(['auth:sanctum', 'branch.access'])->group(function () {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::post('auth/change-password', [AuthController::class, 'changePassword']);
        Route::get('profile', [AuthController::class, 'profile']);
        Route::get('dashboard', [DashboardController::class, 'index']);
        Route::get('portfolio/summary', [PortfolioController::class, 'summary']);
        Route::get('portfolio/branches', [PortfolioController::class, 'branches']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/read-all', [NotificationController::class, 'readAll']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'read']);

        Route::post('onboarding/groups', [OnboardingController::class, 'group']);
        Route::post('onboarding/members', [OnboardingController::class, 'member']);
        Route::post('onboarding/loan-applications', [OnboardingController::class, 'loanApplication']);

        Route::apiResource('regions', RegionController::class)->middleware('role:super_admin|head_office_admin');
        Route::apiResource('areas', AreaController::class)->middleware('role:super_admin|head_office_admin');
        Route::apiResource('branches', BranchController::class)->middleware('role:super_admin|head_office_admin');
        Route::get('roles', [UserController::class, 'roles'])->middleware('role:super_admin|head_office_admin');
        Route::apiResource('users', UserController::class)->middleware('role:super_admin|head_office_admin');
        Route::get('users/{user}/attachments', [UserAttachmentController::class, 'index'])->middleware('role:super_admin|head_office_admin');
        Route::post('users/{user}/attachments', [UserAttachmentController::class, 'store'])->middleware('role:super_admin|head_office_admin');
        Route::get('users/{user}/attachments/{userAttachment}/download', [UserAttachmentController::class, 'download'])->name('api.users.attachments.download')->middleware('role:super_admin|head_office_admin');
        Route::delete('users/{user}/attachments/{userAttachment}', [UserAttachmentController::class, 'destroy'])->middleware('role:super_admin|head_office_admin');
        Route::apiResource('groups', GroupController::class)->only(['index', 'show']);
        Route::apiResource('groups', GroupController::class)->only('store')->middleware('permission:create-groups');
        Route::apiResource('groups', GroupController::class)->only(['update', 'destroy'])->middleware('permission:edit-groups');
        Route::get('groups/{group}/members', [GroupController::class, 'members']);
        Route::get('groups/{group}/dashboard', [GroupPortfolioController::class, 'dashboard']);
        Route::get('groups/{group}/loans', [GroupPortfolioController::class, 'loans']);
        Route::get('groups/{group}/applications', [GroupPortfolioController::class, 'applications']);
        Route::get('groups/{group}/collections', [GroupPortfolioController::class, 'collections']);
        Route::get('groups/{group}/meetings', [GroupPortfolioController::class, 'meetings']);
        Route::apiResource('group-visits', GroupVisitController::class)->middleware('permission:view-group-visits');
        Route::apiResource('members', MemberController::class)->only(['index', 'show']);
        Route::apiResource('members', MemberController::class)->only('store')->middleware('permission:create-members');
        Route::apiResource('members', MemberController::class)->only('update')->middleware('permission:edit-members');
        Route::apiResource('members', MemberController::class)->only('destroy')->middleware('permission:delete-members');
        Route::put('members/{member}/kyc', [MemberKycController::class, 'update'])->middleware('permission:edit-members');
        Route::post('members/{member}/photo', [MemberPhotoController::class, 'store'])->middleware('permission:edit-members');
        Route::get('members/{member}/passbook', [MemberPassbookController::class, 'show']);
        Route::get('members/{member}/export', [MemberExportController::class, 'download']);
        Route::get('members/{member}/documents', [MemberDocumentController::class, 'index']);
        Route::post('members/{member}/documents', [MemberDocumentController::class, 'store'])->middleware('permission:edit-members');
        Route::get('members/{member}/documents/{memberDocument}/download', [MemberDocumentController::class, 'download'])->name('api.members.documents.download');
        Route::delete('members/{member}/documents/{memberDocument}', [MemberDocumentController::class, 'destroy'])->middleware('permission:delete-members');
        Route::get('members/{member}/security', [SecurityAccountController::class, 'show']);
        Route::post('members/{member}/security-transactions', [SecurityAccountController::class, 'store'])->middleware('permission:manage-security');

        Route::apiResource('loan-products', LoanProductController::class)->only(['index', 'show']);
        Route::apiResource('loan-products', LoanProductController::class)->only(['store', 'update', 'destroy'])->middleware('role:super_admin|head_office_admin');
        Route::post('loan-calculator', [LoanCalculatorController::class, 'calculate']);
        Route::apiResource('loan-applications', LoanApplicationController::class)->only(['index', 'show']);
        Route::apiResource('loan-applications', LoanApplicationController::class)->only(['store', 'update', 'destroy'])->middleware('permission:create-loan-applications');
        Route::post('loan-applications/{loanApplication}/submit', [LoanApplicationWorkflowController::class, 'submit'])->middleware('permission:create-loan-applications');
        Route::post('loan-applications/{loanApplication}/approve', [LoanApplicationWorkflowController::class, 'approve'])->middleware('permission:approve-loan-applications');
        Route::post('loan-applications/{loanApplication}/reject', [LoanApplicationWorkflowController::class, 'reject'])->middleware('permission:reject-loan-applications');
        Route::post('loan-applications/{loanApplication}/assign-credit-officer', [CreditReviewController::class, 'assign'])->middleware('permission:review-loan-applications');
        Route::post('loan-applications/{loanApplication}/credit-review', [CreditReviewController::class, 'store'])->middleware('permission:review-loan-applications');
        Route::post('loan-applications/{loanApplication}/return', [CreditReviewController::class, 'returnApplication'])->middleware('permission:review-loan-applications');
        Route::put('loan-applications/{loanApplication}/compliance/applicant', [ApplicationComplianceController::class, 'applicant'])->middleware('permission:manage-loan-compliance');
        Route::post('loan-applications/{loanApplication}/compliance/guarantors', [ApplicationComplianceController::class, 'guarantor'])->middleware('permission:manage-loan-compliance');
        Route::put('loan-applications/{loanApplication}/compliance/nominees', [ApplicationComplianceController::class, 'nominees'])->middleware('permission:manage-loan-compliance');
        Route::post('loan-applications/{loanApplication}/compliance/documents', [ApplicationComplianceController::class, 'document'])->middleware('permission:manage-loan-compliance');
        Route::post('loan-applications/{loanApplication}/compliance/documents/{loanDocument}/verify', [ApplicationComplianceController::class, 'verifyDocument'])->middleware('permission:verify-loan-documents');
        Route::get('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/documents', [ApplicationDocumentController::class, 'store'])->middleware('permission:create-loan-applications');
        Route::post('loan-applications/{loanApplication}/documents/{loanDocument}/verify', [ApplicationDocumentController::class, 'verify'])->middleware('permission:verify-loan-documents');
        Route::get('loan-applications/{loanApplication}/documents/{loanDocument}/download', [ApplicationDocumentController::class, 'download'])->name('api.loan-applications.documents.download');
        Route::get('loan-applications/{loanApplication}/export', [ApplicationExportController::class, 'download']);
        Route::post('loan-applications/{loanApplication}/cancel', [ApplicationComplianceController::class, 'cancel'])->middleware('permission:create-loan-applications');
        Route::get('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'index']);
        Route::post('loan-applications/{loanApplication}/group-witnesses', [LoanGroupWitnessController::class, 'store'])->middleware('permission:manage-group-witnesses');

        Route::get('loans', [LoanController::class, 'index']);
        Route::get('loans/{loan}', [LoanController::class, 'show']);
        Route::get('loans/{loan}/schedule', [LoanController::class, 'schedule']);
        Route::get('loans/{loan}/export', [LoanExportController::class, 'download']);
        Route::post('loans/{loan}/disburse', [LoanDisbursementController::class, 'store'])->middleware('permission:disburse-loans');
        Route::post('loans/{loan}/payments', [PaymentController::class, 'store'])->middleware('permission:collect-payments');
        Route::post('payments/{payment}/reverse', [PaymentController::class, 'reverse'])->middleware('permission:reverse-payments');
        Route::post('loans/{loan}/settle', [LoanSettlementController::class, 'store'])->middleware('permission:settle-loans');
        Route::post('members/{member}/passbook-replacements', [LoanAdministrationController::class, 'replacePassbook'])->middleware('permission:replace-passbooks');
        Route::post('loans/{loan}/default-notices', [LoanAdministrationController::class, 'defaultNotice'])->middleware('permission:issue-default-notices');
        Route::post('loans/{loan}/clearance', [LoanAdministrationController::class, 'clearance'])->middleware('permission:authorize-loan-clearances');

        Route::prefix('system')->middleware('role:super_admin|head_office_admin')->group(function () {
            Route::get('settings', [SystemSettingsController::class, 'index'])->name('api.system.settings.index');
            Route::put('settings', [SystemSettingsController::class, 'update'])->name('api.system.settings.update');
            Route::get('audit-logs', [AuditLogController::class, 'index'])->name('api.system.audit-logs.index');
            Route::get('audit-logs/{id}', [AuditLogController::class, 'show'])->name('api.system.audit-logs.show');
            Route::get('data/summary', [DataPurgeController::class, 'summary'])->name('api.system.data.summary');
            Route::post('data/preview', [DataPurgeController::class, 'preview'])->name('api.system.data.preview');
        });
        Route::post('system/data/purge', [DataPurgeController::class, 'purge'])->name('api.system.data.purge')->middleware('role:super_admin|head_office_admin');
    });
});
