@extends('layouts.admin')
@section('title','Organization')
@section('content')
<div class="page-head"><div><p class="eyebrow">ORGANIZATION STRUCTURE</p><h1>Regions, areas & branches</h1><p>Maintain the operating hierarchy used for access and reporting.</p></div></div>
<div class="grid-2 grid-even">
<div class="card"><div class="card-head"><h2>Add region</h2></div><form class="card-body" method="POST" action="{{ route('admin.regions.store') }}">@csrf<div class="form-grid"><label>Name<input name="name" required></label></div><p class="muted">The region code is generated automatically when saved.</p><div class="form-actions"><button class="btn btn-primary">Save region</button></div></form></div>
<div class="card"><div class="card-head"><h2>Add area</h2></div><form class="card-body" method="POST" action="{{ route('admin.areas.store') }}">@csrf<div class="form-grid"><label>Region<select name="region_id" required><option value="">Select</option>@foreach($regions as $region)<option value="{{ $region->id }}">{{ $region->name }}</option>@endforeach</select></label><label>Name<input name="name" required></label></div><p class="muted">The area code is generated automatically when saved.</p><div class="form-actions"><button class="btn btn-primary">Save area</button></div></form></div>
</div><br>
<div class="card"><div class="card-head"><h2>Add branch</h2></div><form class="card-body" method="POST" action="{{ route('admin.branches.store') }}">@csrf<div class="form-grid"><label>Area<select name="area_id" required>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->region->name }} · {{ $area->name }}</option>@endforeach</select></label><label>Branch name<input name="branch_name" required></label><label>Phone<input name="phone"></label><label>Email<input type="email" name="email"></label><label>Address<input name="address"></label></div><p class="muted">The branch code is generated automatically when saved.</p><div class="form-actions"><button class="btn btn-primary">Create branch</button></div></form></div><br>
<div class="card"><div class="card-head"><h2>Branch directory</h2><span class="muted">{{ $branches->count() }} branches</span></div><div class="table-wrap"><table><thead><tr><th>Branch</th><th>Area / Region</th><th>Members</th><th>Groups</th><th>Status</th></tr></thead><tbody>@forelse($branches as $branch)<tr><td><strong>{{ $branch->branch_name }}</strong><br><small class="muted">{{ $branch->branch_code }}</small></td><td>{{ $branch->area?->name }} / {{ $branch->area?->region?->name }}</td><td>{{ number_format($branch->members_count) }}</td><td>{{ number_format($branch->groups_count) }}</td><td><span class="badge {{ $branch->status?'active':'inactive' }}">{{ $branch->status?'Active':'Inactive' }}</span></td></tr>@empty<tr><td colspan="5" class="empty">Create your first branch above.</td></tr>@endforelse</tbody></table></div></div>
@endsection
