@extends('layouts.admin')
@section('title',$application->application_number)
@section('content')
@php($status=$application->status->value)
<div class="page-head"><div><p class="eyebrow">{{ $application->application_number }}</p><h1>{{ $application->member->first_name }} {{ $application->member->last_name }}</h1><p>{{ $application->product->name }} · {{ $application->group->group_name }}</p></div><div class="head-actions"><span class="badge {{ $status }}">{{ str_replace('_',' ',$status) }}</span>@if($status==='draft')<form method="POST" action="{{ route('admin.loan-applications.submit',$application) }}">@csrf<button class="btn btn-primary">Submit for review</button></form>@endif @if($application->loan)<a class="btn btn-primary" href="{{ route('admin.loans.show',$application->loan) }}">Open loan →</a>@endif</div></div>
<div class="stats"><div class="stat gold"><small>Requested amount</small><strong>TZS {{ number_format($application->requested_amount) }}</strong></div><div class="stat"><small>Duration</small><strong>{{ $application->duration_months }} months</strong></div><div class="stat"><small>Witness progress</small><strong>{{ $application->groupWitnesses->count() }} / {{ $application->product->required_group_witnesses }}</strong><div class="progress"><span style="width:{{ $application->product->required_group_witnesses?min(100,$application->groupWitnesses->count()/$application->product->required_group_witnesses*100):100 }}%"></span></div></div><div class="stat"><small>Disposable income</small><strong>TZS {{ number_format($application->assessment?->disposable_income??0) }}</strong></div></div>
<div class="grid-2"><div><div class="card"><div class="card-head"><h2>Application details</h2></div><div class="card-body detail-grid"><div class="detail"><small>Member number</small><strong><a class="table-link" href="{{ route('admin.members.show',$application->member) }}">{{ $application->member->membership_number }}</a></strong></div><div class="detail"><small>Branch</small><strong>{{ $application->branch->branch_name }}</strong></div><div class="detail"><small>Group</small><strong>{{ $application->group->group_name }}</strong></div><div class="detail"><small>Type</small><strong>{{ ucfirst($application->application_type) }}</strong></div><div class="detail"><small>Purpose</small><strong>{{ $application->loan_purpose?:'—' }}</strong></div><div class="detail"><small>Submitted</small><strong>{{ $application->submitted_at?->format('d M Y H:i')??'Not submitted' }}</strong></div></div></div><br>
<div class="card"><div class="card-head"><h2>Approval history</h2></div><div class="table-wrap"><table><thead><tr><th>Decision</th><th>Officer</th><th>Remarks</th><th>Time</th></tr></thead><tbody>@forelse($application->approvals as $approval)<tr><td><span class="badge {{ $approval->decision }}">{{ $approval->decision }}</span></td><td>{{ $approval->user->name }}</td><td>{{ $approval->remarks?:'—' }}</td><td>{{ $approval->acted_at->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="empty">No approval action yet.</td></tr>@endforelse</tbody></table></div></div></div>
<div><div class="card"><div class="card-head"><h2>Group witnesses</h2><span>{{ $application->groupWitnesses->count() }} confirmed</span></div><div class="card-body">@forelse($application->groupWitnesses as $witness)<div class="detail" style="margin-bottom:8px"><small>Confirmed {{ $witness->confirmed_at->format('d M Y H:i') }}</small><strong>{{ $witness->member->first_name }} {{ $witness->member->last_name }}</strong></div>@empty<p class="muted">No witnesses confirmed yet.</p>@endforelse @if(!in_array($status,['approved','rejected','disbursed']))<form method="POST" action="{{ route('admin.loan-applications.witnesses.store',$application) }}">@csrf<label>Add eligible witness<select name="member_id" required><option value="">Select group member</option>@foreach($eligibleWitnesses as $witness)<option value="{{ $witness->id }}">{{ $witness->membership_number }} · {{ $witness->first_name }} {{ $witness->last_name }}</option>@endforeach</select></label><div class="form-actions"><button class="btn btn-gold">Confirm witness</button></div></form>@endif</div></div><br>
@if(in_array($status,['submitted','lo_review','abm_review','bm_review','credit_review']))<div class="card"><div class="card-head"><h2>Credit decision</h2></div><div class="card-body"><form method="POST" action="{{ route('admin.loan-applications.approve',$application) }}">@csrf<label>Approval remarks<textarea name="remarks"></textarea></label><div class="form-actions"><button class="btn btn-primary" data-confirm="Approve this loan application?">Approve application</button></div></form><form method="POST" action="{{ route('admin.loan-applications.reject',$application) }}">@csrf<label>Rejection reason<textarea name="remarks" required></textarea></label><div class="form-actions"><button class="btn btn-danger" data-confirm="Reject this loan application?">Reject application</button></div></form></div></div>@endif</div></div>
@endsection
